### ISSUE TITLE
Inclusión de mecanismo de tracking para MongoDB

### ISSUE THREAD

**Issue by jonatanvicente** [IT-Academy-BCN/ita-challenges-backend#441]
Es necesario añadir una librería / mecanismo de tracking para cambios ejecutados en scripts de DBs sobre Mongo.
Esto afecta a los micros Challenge, User, y quizá otros en el futuro.

**Parcialmente implementado en feature#441**

**PROCEDIMIENTO INICIAL**

- Es necesario testear el workflow a seguir cuando hay un cambio en base de datos. Hay que tener presente que:
   - Mongo está dando un stream reactivo
   - El driver para mongock es también reactivo

**Comment by ArcosErnesto** [comment]
![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/146434844/88d1cddf-3101-4b11-bbf3-892bc13d9b9e)

**Comment by ArcosErnesto** [comment]
![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/146434844/4715fccb-61b2-4145-af5e-c5552f06b343)

**Comment by ArcosErnesto** [comment]
![Image](https://github.com/IT-Academy-BCN/ita-challenges-backend/assets/146434844/7e530309-e275-4dc3-bd22-eaecf7195d7b)

**Comment by ArcosErnesto** [comment]
Valoramos la opción de usar Mongock en lugar de Mongobee (https://docs.mongock.io/)

**Comment by plopezgit** [comment]
Notas posibles acciones daily:

- [x] Replicar el timeout cortando la instancia de mongo en local
- [x] Probar la creacion de una clase de config especial de mongock (Referencia: https://github.com/mongock/mongock-examples/tree/master/mongodb/springboot-advance/src/main/java/io/mongock/examples/mongodb/springboot/advance/config)
- [x] Consultar copilot sobre advices/alternative to config libreria fuera de contexto de test
- [x] El punto anterior puede estar relacionado con el set de un "profile" especial (investigar)
- [x] En base al punto anterior la clase de configuracion de mongock se nota con @Profile("!test") y la application.yml de test:   profiles.active: test
- [x] Ver/estudiar esfuerzo para crear un perfil especial para mongock
- [x] Crear un usuario de acceso a mongo especial para mongock (no required so far)

@ArcosErnesto 
@jonatanvicente

**Comment by jonatanvicente** [comment]
**FASES DE REVISIÓN**

- Crear una nueva rama a partir de feature#441 implementada para trabajar.
- Eliminar los tests, incluidos sus config files.
- Verificar que lo implementado hasta ahora funciona en fase dev
- Corregir configuración (hay varios application.yml)
- Añadir tests:
   - Añadir Test Container y verificar su funcionamiento (véanse tests de repository, OJO al cierre de contexto MongoDB).
   - Creación de application.yml de tests (si es necesario). Inyectar configuración a mongock para que ataque a Test Container. *NOTA*: es posible que haya que efectuar la configuración vía programática, no sólo con config files
